version: '3.3'

volumes:
  mongo-data:

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081