version: '3.3'

networks:
  net:
    driver: bridge

volumes:
  mongo-data:

services:
  mongo:
    image: mongo:4
    volumes:
      - mongo-data:/data/db
    networks:
      - net

  mongo-express:
    image: mongo-express:latest
    networks:
      - net
    depends_on:
      - mongo
    ports:
      - 8081:8081

  api:
    build: .
    networks:
      - net
    depends_on:
      - mongo
    environment:
      MONGODB_URL: mongodb://mongo:27017
      MONGODB_DBNAME: api-bal
      NODE_ENV: development
    ports:
      - 5000:5000
